# Generated by Django 3.1.5 on 2021-02-13 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(default=datetime.datetime(2021, 2, 13, 13, 2, 31, 935416, tzinfo=utc), verbose_name='Время добавления')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('key_words', models.CharField(default='---', max_length=50, verbose_name='Ключевые слова')),
                ('info', models.CharField(default='---', max_length=1000, verbose_name='Комментарии')),
                ('photo', sorl.thumbnail.fields.ImageField(default='no_image.png', upload_to='photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
