# Generated by Django 3.1.6 on 2021-02-13 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 17, 8, 13, 723323, tzinfo=utc), verbose_name='Время добавления'),
        ),
    ]
